data = {
    "americanpundits": [
                "data/americanpundits_desktop.csv",
                "data/americanpundits_desktopspider.csv",
                "data/americanpundits_mobileapp.csv",
                "data/americanpundits_mobile.csv",
                "data/americanpundits_mobilespider.csv",
        ],
    "cities": [
                "data/cities_desktop.csv",
                "data/cities_desktopspider.csv",
                "data/cities_mobileapp.csv",
                "data/cities_mobile.csv",
                "data/cities_mobilespider.csv",
        ],
    "colors": [
                "data/colors_desktop.csv",
                "data/colors_desktopspider.csv",
                "data/colors_mobileapp.csv",
                "data/colors_mobile.csv",
                "data/colors_mobilespider.csv",
        ],
    "compilertheory": [
                "data/compilertheory_desktop.csv",
                "data/compilertheory_desktopspider.csv",
                "data/compilertheory_mobileapp.csv",
                "data/compilertheory_mobile.csv",
                "data/compilertheory_mobilespider.csv",
        ],
    "countries": [
                "data/countries_desktop.csv",
                "data/countries_desktopspider.csv",
                "data/countries_mobileapp.csv",
                "data/countries_mobile.csv",
                "data/countries_mobilespider.csv",
        ],
    "eggplantdishes": [
                "data/eggplantdishes_desktop.csv",
                "data/eggplantdishes_desktopspider.csv",
                "data/eggplantdishes_mobileapp.csv",
                "data/eggplantdishes_mobile.csv",
                "data/eggplantdishes_mobilespider.csv",
        ],
    "french_colors": [
                "data/french_colors_desktop.csv",
                "data/french_colors_desktopspider.csv",
                "data/french_colors_mobileapp.csv",
                "data/french_colors_mobile.csv",
                "data/french_colors_mobilespider.csv",
        ],
    "german_colors": [
                "data/german_colors_desktop.csv",
                "data/german_colors_desktopspider.csv",
                "data/german_colors_mobileapp.csv",
                "data/german_colors_mobile.csv",
                "data/german_colors_mobilespider.csv",
        ],
    "musicians": [
                "data/musicians_desktop.csv",
                "data/musicians_desktopspider.csv",
                "data/musicians_mobileapp.csv",
                "data/musicians_mobile.csv",
                "data/musicians_mobilespider.csv",
        ],
    "philanthropicfoundations": [
                "data/philanthropicfoundations_desktop.csv",
                "data/philanthropicfoundations_desktopspider.csv",
                "data/philanthropicfoundations_mobileapp.csv",
                "data/philanthropicfoundations_mobile.csv",
                "data/philanthropicfoundations_mobilespider.csv",
        ],
    "programminglanguages": [
                "data/programminglanguages_desktop.csv",
                "data/programminglanguages_desktopspider.csv",
                "data/programminglanguages_mobileapp.csv",
                "data/programminglanguages_mobile.csv",
                "data/programminglanguages_mobilespider.csv",
        ],
    "sexorgans": [
                "data/sexorgans_desktop.csv",
                "data/sexorgans_desktopspider.csv",
                "data/sexorgans_mobileapp.csv",
                "data/sexorgans_mobile.csv",
                "data/sexorgans_mobilespider.csv",
        ],
    "shooting": [
                "data/shooting_desktop.csv",
                "data/shooting_desktopspider.csv",
                "data/shooting_mobileapp.csv",
                "data/shooting_mobile.csv",
                "data/shooting_mobilespider.csv",
        ],
    "spanish_colors": [
                "data/spanish_colors_desktop.csv",
                "data/spanish_colors_desktopspider.csv",
                "data/spanish_colors_mobileapp.csv",
                "data/spanish_colors_mobile.csv",
                "data/spanish_colors_mobilespider.csv",
        ],
    "uspoliticians": [
                "data/uspoliticians_desktop.csv",
                "data/uspoliticians_desktopspider.csv",
                "data/uspoliticians_mobileapp.csv",
                "data/uspoliticians_mobile.csv",
                "data/uspoliticians_mobilespider.csv",
        ],
    "uspresidents": [
                "data/uspresidents_desktop.csv",
                "data/uspresidents_desktopspider.csv",
                "data/uspresidents_mobileapp.csv",
                "data/uspresidents_mobile.csv",
                "data/uspresidents_mobilespider.csv",
        ],
}
